builder:
  track: dev

labels:
  app: estafette-ci-contracts
  app-group: estafette-ci
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 0
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

stages:
  build:
    image: golang:1.10.3-alpine3.8
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - apk --no-cache add git protobuf-dev
    - go get -u google.golang.org/grpc
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - go test -v `go list ./... | grep -v /vendor/`

  # protoc:
  #   image: golang:1.10.3-alpine3.8
  #   workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
  #   commands:
  #   - apk --no-cache add git protobuf-dev
  #   - go get -u google.golang.org/grpc
  #   - go get -u github.com/golang/protobuf/protoc-gen-go
  #   - protoc --go_out=plugins=grpc:grpc *.proto
  #   - ls -latr grpc/*.pb.go

  tag-revision:
    image: golang:1.10.3-alpine3.8
    commands:
    - apk --no-cache add git
    - git tag ${ESTAFETTE_BUILD_VERSION}
    - git push origin ${ESTAFETTE_BUILD_VERSION}

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(PiUCBMW1LEeyFk3i.vn0sEYGK_QU_tXtxQ7PbQra1L8a-reYGkDbzP9K9A6NzKbsf4CExtahJW7JjViXCtxuRlAt_c4kYF2oBRaCQ_4x3iDWLUp4P7AkchXI9Es4l7eeUWfB3A-Lpy4LG)
    name: ${ESTAFETTE_LABEL_APP}
    channels:
    - '#build-status'
    when:
      status == 'failed'
