// Code generated by protoc-gen-go. DO NOT EDIT.
// source: estafette_ci_api.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BuildLog struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoSource           string               `protobuf:"bytes,2,opt,name=repo_source,json=repoSource,proto3" json:"repo_source,omitempty"`
	RepoOwner            string               `protobuf:"bytes,3,opt,name=repo_owner,json=repoOwner,proto3" json:"repo_owner,omitempty"`
	RepoName             string               `protobuf:"bytes,4,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoBranch           string               `protobuf:"bytes,5,opt,name=repo_branch,json=repoBranch,proto3" json:"repo_branch,omitempty"`
	RepoRevision         string               `protobuf:"bytes,6,opt,name=repo_revision,json=repoRevision,proto3" json:"repo_revision,omitempty"`
	Steps                []*BuildLogStep      `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	InsertedAt           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=inserted_at,json=insertedAt,proto3" json:"inserted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BuildLog) Reset()         { *m = BuildLog{} }
func (m *BuildLog) String() string { return proto.CompactTextString(m) }
func (*BuildLog) ProtoMessage()    {}
func (*BuildLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_estafette_ci_api_5dd1e1e05d35f5c6, []int{0}
}
func (m *BuildLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildLog.Unmarshal(m, b)
}
func (m *BuildLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildLog.Marshal(b, m, deterministic)
}
func (dst *BuildLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildLog.Merge(dst, src)
}
func (m *BuildLog) XXX_Size() int {
	return xxx_messageInfo_BuildLog.Size(m)
}
func (m *BuildLog) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildLog.DiscardUnknown(m)
}

var xxx_messageInfo_BuildLog proto.InternalMessageInfo

func (m *BuildLog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BuildLog) GetRepoSource() string {
	if m != nil {
		return m.RepoSource
	}
	return ""
}

func (m *BuildLog) GetRepoOwner() string {
	if m != nil {
		return m.RepoOwner
	}
	return ""
}

func (m *BuildLog) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *BuildLog) GetRepoBranch() string {
	if m != nil {
		return m.RepoBranch
	}
	return ""
}

func (m *BuildLog) GetRepoRevision() string {
	if m != nil {
		return m.RepoRevision
	}
	return ""
}

func (m *BuildLog) GetSteps() []*BuildLogStep {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *BuildLog) GetInsertedAt() *timestamp.Timestamp {
	if m != nil {
		return m.InsertedAt
	}
	return nil
}

type BuildLogStep struct {
	Step                 string                   `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Image                *BuildLogStepDockerImage `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Duration             *duration.Duration       `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	LogLines             []*BuildLogLine          `protobuf:"bytes,4,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"`
	ExitCode             int64                    `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Status               string                   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	AutoInjected         bool                     `protobuf:"varint,7,opt,name=auto_injected,json=autoInjected,proto3" json:"auto_injected,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BuildLogStep) Reset()         { *m = BuildLogStep{} }
func (m *BuildLogStep) String() string { return proto.CompactTextString(m) }
func (*BuildLogStep) ProtoMessage()    {}
func (*BuildLogStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_estafette_ci_api_5dd1e1e05d35f5c6, []int{1}
}
func (m *BuildLogStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildLogStep.Unmarshal(m, b)
}
func (m *BuildLogStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildLogStep.Marshal(b, m, deterministic)
}
func (dst *BuildLogStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildLogStep.Merge(dst, src)
}
func (m *BuildLogStep) XXX_Size() int {
	return xxx_messageInfo_BuildLogStep.Size(m)
}
func (m *BuildLogStep) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildLogStep.DiscardUnknown(m)
}

var xxx_messageInfo_BuildLogStep proto.InternalMessageInfo

func (m *BuildLogStep) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *BuildLogStep) GetImage() *BuildLogStepDockerImage {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *BuildLogStep) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *BuildLogStep) GetLogLines() []*BuildLogLine {
	if m != nil {
		return m.LogLines
	}
	return nil
}

func (m *BuildLogStep) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *BuildLogStep) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BuildLogStep) GetAutoInjected() bool {
	if m != nil {
		return m.AutoInjected
	}
	return false
}

type BuildLogStepDockerImage struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string             `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	IsPulled             bool               `protobuf:"varint,3,opt,name=is_pulled,json=isPulled,proto3" json:"is_pulled,omitempty"`
	ImageSize            int64              `protobuf:"varint,4,opt,name=image_size,json=imageSize,proto3" json:"image_size,omitempty"`
	PullDuration         *duration.Duration `protobuf:"bytes,5,opt,name=pull_duration,json=pullDuration,proto3" json:"pull_duration,omitempty"`
	Error                string             `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	IsTrusted            bool               `protobuf:"varint,7,opt,name=is_trusted,json=isTrusted,proto3" json:"is_trusted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BuildLogStepDockerImage) Reset()         { *m = BuildLogStepDockerImage{} }
func (m *BuildLogStepDockerImage) String() string { return proto.CompactTextString(m) }
func (*BuildLogStepDockerImage) ProtoMessage()    {}
func (*BuildLogStepDockerImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_estafette_ci_api_5dd1e1e05d35f5c6, []int{2}
}
func (m *BuildLogStepDockerImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildLogStepDockerImage.Unmarshal(m, b)
}
func (m *BuildLogStepDockerImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildLogStepDockerImage.Marshal(b, m, deterministic)
}
func (dst *BuildLogStepDockerImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildLogStepDockerImage.Merge(dst, src)
}
func (m *BuildLogStepDockerImage) XXX_Size() int {
	return xxx_messageInfo_BuildLogStepDockerImage.Size(m)
}
func (m *BuildLogStepDockerImage) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildLogStepDockerImage.DiscardUnknown(m)
}

var xxx_messageInfo_BuildLogStepDockerImage proto.InternalMessageInfo

func (m *BuildLogStepDockerImage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuildLogStepDockerImage) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *BuildLogStepDockerImage) GetIsPulled() bool {
	if m != nil {
		return m.IsPulled
	}
	return false
}

func (m *BuildLogStepDockerImage) GetImageSize() int64 {
	if m != nil {
		return m.ImageSize
	}
	return 0
}

func (m *BuildLogStepDockerImage) GetPullDuration() *duration.Duration {
	if m != nil {
		return m.PullDuration
	}
	return nil
}

func (m *BuildLogStepDockerImage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BuildLogStepDockerImage) GetIsTrusted() bool {
	if m != nil {
		return m.IsTrusted
	}
	return false
}

type BuildLogLine struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StreamType           string               `protobuf:"bytes,2,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"`
	Text                 string               `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BuildLogLine) Reset()         { *m = BuildLogLine{} }
func (m *BuildLogLine) String() string { return proto.CompactTextString(m) }
func (*BuildLogLine) ProtoMessage()    {}
func (*BuildLogLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_estafette_ci_api_5dd1e1e05d35f5c6, []int{3}
}
func (m *BuildLogLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildLogLine.Unmarshal(m, b)
}
func (m *BuildLogLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildLogLine.Marshal(b, m, deterministic)
}
func (dst *BuildLogLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildLogLine.Merge(dst, src)
}
func (m *BuildLogLine) XXX_Size() int {
	return xxx_messageInfo_BuildLogLine.Size(m)
}
func (m *BuildLogLine) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildLogLine.DiscardUnknown(m)
}

var xxx_messageInfo_BuildLogLine proto.InternalMessageInfo

func (m *BuildLogLine) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BuildLogLine) GetStreamType() string {
	if m != nil {
		return m.StreamType
	}
	return ""
}

func (m *BuildLogLine) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildLog)(nil), "estafette.ci.contracts.BuildLog")
	proto.RegisterType((*BuildLogStep)(nil), "estafette.ci.contracts.BuildLogStep")
	proto.RegisterType((*BuildLogStepDockerImage)(nil), "estafette.ci.contracts.BuildLogStepDockerImage")
	proto.RegisterType((*BuildLogLine)(nil), "estafette.ci.contracts.BuildLogLine")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EstafetteCiApiClient is the client API for EstafetteCiApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EstafetteCiApiClient interface {
	CreatePipelineBuildLogs(ctx context.Context, in *BuildLog, opts ...grpc.CallOption) (*empty.Empty, error)
}

type estafetteCiApiClient struct {
	cc *grpc.ClientConn
}

func NewEstafetteCiApiClient(cc *grpc.ClientConn) EstafetteCiApiClient {
	return &estafetteCiApiClient{cc}
}

func (c *estafetteCiApiClient) CreatePipelineBuildLogs(ctx context.Context, in *BuildLog, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/estafette.ci.contracts.EstafetteCiApi/CreatePipelineBuildLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EstafetteCiApiServer is the server API for EstafetteCiApi service.
type EstafetteCiApiServer interface {
	CreatePipelineBuildLogs(context.Context, *BuildLog) (*empty.Empty, error)
}

func RegisterEstafetteCiApiServer(s *grpc.Server, srv EstafetteCiApiServer) {
	s.RegisterService(&_EstafetteCiApi_serviceDesc, srv)
}

func _EstafetteCiApi_CreatePipelineBuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstafetteCiApiServer).CreatePipelineBuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/estafette.ci.contracts.EstafetteCiApi/CreatePipelineBuildLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstafetteCiApiServer).CreatePipelineBuildLogs(ctx, req.(*BuildLog))
	}
	return interceptor(ctx, in, info, handler)
}

var _EstafetteCiApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "estafette.ci.contracts.EstafetteCiApi",
	HandlerType: (*EstafetteCiApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePipelineBuildLogs",
			Handler:    _EstafetteCiApi_CreatePipelineBuildLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "estafette_ci_api.proto",
}

func init() {
	proto.RegisterFile("estafette_ci_api.proto", fileDescriptor_estafette_ci_api_5dd1e1e05d35f5c6)
}

var fileDescriptor_estafette_ci_api_5dd1e1e05d35f5c6 = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x66, 0x7f, 0x9b, 0x38, 0xdb, 0x0a, 0x59, 0xa8, 0x0d, 0x5b, 0x41, 0x57, 0x0b, 0x87, 0x3d,
	0xa5, 0xd2, 0x22, 0x24, 0x04, 0x12, 0x52, 0xff, 0x0e, 0x95, 0x2a, 0xa8, 0xd2, 0x72, 0xe1, 0x62,
	0xb9, 0xc9, 0x34, 0x18, 0x92, 0xd8, 0xb2, 0x27, 0xd0, 0xad, 0xc4, 0x6b, 0x71, 0xe3, 0x9d, 0x78,
	0x04, 0x64, 0x27, 0xd9, 0x45, 0x2d, 0xd0, 0xde, 0x66, 0xbe, 0xf9, 0x66, 0x32, 0xf3, 0xcd, 0x38,
	0x64, 0x13, 0x0c, 0xf2, 0x4b, 0x40, 0x04, 0x96, 0x08, 0xc6, 0x95, 0x88, 0x94, 0x96, 0x28, 0xe9,
	0x0a, 0x8f, 0x12, 0x11, 0x25, 0xb2, 0x44, 0xcd, 0x13, 0x34, 0xe3, 0xed, 0x4c, 0xca, 0x2c, 0x87,
	0x5d, 0xc7, 0xba, 0xa8, 0x2e, 0x77, 0xa1, 0x50, 0xb8, 0xa8, 0x93, 0xc6, 0x3b, 0x37, 0x83, 0x28,
	0x0a, 0x5b, 0xa7, 0x50, 0x0d, 0xe1, 0xe9, 0x4d, 0x42, 0x5a, 0x69, 0x8e, 0x42, 0x96, 0x75, 0x7c,
	0xfa, 0xa3, 0x4b, 0xbc, 0xfd, 0x4a, 0xe4, 0xe9, 0x89, 0xcc, 0xe8, 0x06, 0xe9, 0x8a, 0x34, 0xec,
	0x4c, 0x3a, 0x33, 0x3f, 0xee, 0x8a, 0x94, 0xee, 0x90, 0x40, 0x83, 0x92, 0xcc, 0xc8, 0x4a, 0x27,
	0x10, 0x76, 0x5d, 0x80, 0x58, 0xe8, 0xcc, 0x21, 0xf4, 0x09, 0x71, 0x1e, 0x93, 0xdf, 0x4a, 0xd0,
	0x61, 0xcf, 0xc5, 0x7d, 0x8b, 0xbc, 0xb7, 0x00, 0xdd, 0x26, 0xce, 0x61, 0x25, 0x2f, 0x20, 0xec,
	0xbb, 0xa8, 0x67, 0x81, 0x77, 0xbc, 0x80, 0x65, 0xf1, 0x0b, 0xcd, 0xcb, 0xe4, 0x53, 0x38, 0x58,
	0x15, 0xdf, 0x77, 0x08, 0x7d, 0x46, 0xd6, 0x1d, 0x41, 0xc3, 0x57, 0x61, 0x84, 0x2c, 0xc3, 0xa1,
	0xa3, 0x8c, 0x2c, 0x18, 0x37, 0x18, 0x7d, 0x4d, 0x06, 0x06, 0x41, 0x99, 0x70, 0x6d, 0xd2, 0x9b,
	0x05, 0xf3, 0xe7, 0xd1, 0xdf, 0x55, 0x8c, 0xda, 0x19, 0xcf, 0x10, 0x54, 0x5c, 0xa7, 0xd0, 0x37,
	0x24, 0x10, 0xa5, 0x01, 0x8d, 0x90, 0x32, 0x8e, 0xa1, 0x37, 0xe9, 0xcc, 0x82, 0xf9, 0x38, 0xaa,
	0x15, 0x8b, 0x5a, 0xc5, 0xa2, 0xf3, 0x56, 0xd2, 0x98, 0xb4, 0xf4, 0x3d, 0x9c, 0xfe, 0xec, 0x92,
	0xd1, 0x9f, 0x45, 0x29, 0x25, 0x7d, 0x5b, 0xb6, 0x91, 0xcf, 0xd9, 0xf4, 0x88, 0x0c, 0x44, 0xc1,
	0xb3, 0x5a, 0xba, 0x60, 0xbe, 0x7b, 0x9f, 0xee, 0x0e, 0x65, 0xf2, 0x05, 0xf4, 0xb1, 0x4d, 0x8b,
	0xeb, 0x6c, 0xfa, 0x92, 0x78, 0xed, 0xda, 0x9c, 0xc8, 0xc1, 0xfc, 0xf1, 0xad, 0x2e, 0x0f, 0x1b,
	0x42, 0xbc, 0xa4, 0xd2, 0x3d, 0xe2, 0xe7, 0x32, 0x63, 0xb9, 0x28, 0xc1, 0x84, 0xfd, 0xfb, 0xe9,
	0x73, 0x22, 0x4a, 0x88, 0xbd, 0xbc, 0x36, 0x8c, 0xdd, 0x20, 0x5c, 0x09, 0x64, 0x89, 0x4c, 0xc1,
	0xad, 0xa8, 0x17, 0x7b, 0x16, 0x38, 0x90, 0x29, 0xd0, 0x4d, 0x32, 0x34, 0xc8, 0xb1, 0x32, 0xcd,
	0x66, 0x1a, 0xcf, 0x2e, 0x8e, 0x57, 0x28, 0x99, 0x28, 0x3f, 0x43, 0x82, 0x90, 0x86, 0x6b, 0x93,
	0xce, 0xcc, 0x8b, 0x47, 0x16, 0x3c, 0x6e, 0xb0, 0xe9, 0xaf, 0x0e, 0xd9, 0xfa, 0xc7, 0xd8, 0x56,
	0x4a, 0x77, 0x32, 0x8d, 0x94, 0xd6, 0xa6, 0x0f, 0x49, 0x0f, 0x79, 0xd6, 0xdc, 0xa0, 0x35, 0x6d,
	0x6f, 0xc2, 0x30, 0x55, 0xe5, 0x39, 0xa4, 0x4e, 0x16, 0x2f, 0xf6, 0x84, 0x39, 0x75, 0xbe, 0xbd,
	0x4c, 0xa7, 0x1d, 0x33, 0xe2, 0xba, 0xbe, 0xbd, 0x5e, 0xec, 0x3b, 0xe4, 0x4c, 0x5c, 0x03, 0x7d,
	0x4b, 0xd6, 0x6d, 0x22, 0x5b, 0xca, 0x3a, 0xb8, 0x4b, 0xd6, 0x91, 0xe5, 0xb7, 0x1e, 0x7d, 0x44,
	0x06, 0xa0, 0xb5, 0xd4, 0xcd, 0xe4, 0xb5, 0xe3, 0x3e, 0x6a, 0x18, 0xea, 0xca, 0xac, 0xa6, 0xf6,
	0x85, 0x39, 0xaf, 0x81, 0xe9, 0xf7, 0xd5, 0xc5, 0x58, 0x75, 0xe9, 0x2b, 0xe2, 0x2f, 0x9f, 0xab,
	0x9b, 0xf5, 0xff, 0xd7, 0xb7, 0x22, 0xdb, 0xb7, 0x63, 0x50, 0x03, 0x2f, 0x18, 0x2e, 0xd4, 0xf2,
	0x61, 0xd6, 0xd0, 0xf9, 0x42, 0x39, 0x05, 0x11, 0xae, 0xb0, 0x79, 0x92, 0xce, 0x9e, 0x67, 0x64,
	0xe3, 0xa8, 0x5d, 0xfe, 0x81, 0xd8, 0x53, 0x82, 0x7e, 0x20, 0x5b, 0x07, 0x1a, 0x38, 0xc2, 0xa9,
	0x50, 0x60, 0xcf, 0xa4, 0x6d, 0xcf, 0xd0, 0xc9, 0x5d, 0x87, 0x32, 0xde, 0xbc, 0xd5, 0xea, 0x91,
	0xfd, 0x31, 0x4d, 0x1f, 0xec, 0x0f, 0x3f, 0xf6, 0x33, 0xad, 0x92, 0x8b, 0xa1, 0x8b, 0xbc, 0xf8,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x58, 0xd6, 0x04, 0x52, 0xf2, 0x04, 0x00, 0x00,
}
