#!/bin/sh

# remove all current pb.go files
echo "Pre-commit: removing all pb.go files"
rm -f *.pb.go

# create grpc files for golang
echo "Pre-commit: generating pb.go files"
protoc --go_out=plugins=grpc:. *.proto

# add (or delete) all pb.go files
echo "Pre-commit: adding new or modified pb.go files"
git add *.pb.go -A